export enum TipoNegocio {
    PANADERIA = "PANADERIA",
    CAFETERIA = "CAFETERIA",
    OTRO = "OTRO",
    BAR = "BAR",
    RESTAURANTE = "RESTAURANTE",
    DISCOTECA = "DISCOTECA",
    SUPERMERCADO = "SUPERMERCADO",
    TIENDA = "TIENDA"
}